language: swift
osx_image: xcode10.2

script:
- swift package generate-xcodeproj
- xcodebuild test -scheme Futura-Package -configuration Release -enableCodeCoverage YES -enableThreadSanitizer YES

after_success:
- curl -s https://codecov.io/bash | bash